spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsSystem?useUnicode=true&characterEncoding=UTF8&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create